[package]
name = "cctmux-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cctmux-protocol = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
